name: customer_journey
version: '1.0.0'
config-version: 2
profile: customer_journey

model-paths: ["models"]

models:
  customer_journey:
    raw_layer:
      +materialized: table
      Policy:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: ID
      ChangeEvent:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: ID
      Survey:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: ID
      Contact:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: ID
    metric_layer:
      +materialized: table
    wide_layer:
      +materialized: table
    view_layer:
      +materialized: view