-- WIDE LAYER: ChangeEvent Wide Table
-- AUTO-GENERATED by tools/generate_wide_layer.py — DO NOT EDIT BY HAND.
-- Regenerate after adding/removing a file in models/metric_layer/ChangeEvent_Metrics/:
--   python3 tools/generate_wide_layer.py --entity ChangeEvent
-- Auto-assembly: one OBJECT per relation (raw + each metric model).
-- No combiner. No hand-maintained column list. Metric OBJECTs carry the
-- measure only — the join key ID is implicit (never selected from the
-- metric model directly, so it never needs stripping).
-- Consumer access: ChangeEventWide.ChangeEvent:<Field> / ChangeEventWide.<MetricName>:<MetricName> / ...

SELECT
    ChangeEvent.ChangeEvent AS ChangeEvent
    , OBJECT_CONSTRUCT_KEEP_NULL('InForce90DaysAfterChangeFlag', InForce90DaysAfterChangeFlag.InForce90DaysAfterChangeFlag)::OBJECT(InForce90DaysAfterChangeFlag NUMBER) AS InForce90DaysAfterChangeFlag
    , OBJECT_CONSTRUCT_KEEP_NULL('IsAgentChangeEvent', IsAgentChangeEvent.IsAgentChangeEvent)::OBJECT(IsAgentChangeEvent NUMBER) AS IsAgentChangeEvent
    , OBJECT_CONSTRUCT_KEEP_NULL('IsZipChangeEvent', IsZipChangeEvent.IsZipChangeEvent)::OBJECT(IsZipChangeEvent NUMBER) AS IsZipChangeEvent
FROM {{ ref('ChangeEventRaw') }} AS ChangeEvent
LEFT JOIN {{ ref('InForce90DaysAfterChangeFlag') }} AS InForce90DaysAfterChangeFlag
    ON ChangeEvent.ID = InForce90DaysAfterChangeFlag.ID
LEFT JOIN {{ ref('IsAgentChangeEvent') }} AS IsAgentChangeEvent
    ON ChangeEvent.ID = IsAgentChangeEvent.ID
LEFT JOIN {{ ref('IsZipChangeEvent') }} AS IsZipChangeEvent
    ON ChangeEvent.ID = IsZipChangeEvent.ID
