-- WIDE LAYER: ChangeEvent Wide Table (AUTO-GENERATED)
-- AUTO-GENERATED by tools/generate_wide_layer.py — DO NOT EDIT BY HAND.
-- Snowflake OBJECT_CONSTRUCT(alias.*) — qualified wildcard, auto-expanding.
-- No explicit column list, no logic, zero maintenance.
-- Regenerate after adding/removing a file in models/metric_layer/ChangeEvent_Metrics/:
--   python3 tools/generate_metrics_combiner.py --entity ChangeEvent
--   python3 tools/generate_wide_layer.py --entity ChangeEvent
-- (run the combiner generator FIRST — the wide layer joins against
-- its output, change_event_metrics, not the individual metric files.)
-- Owner: CI/CD (mechanically generated, do not edit by hand)
--
-- HOW IT WORKS (Snowflake):
--   OBJECT_CONSTRUCT(ChangeEvent.*) packs the entire row from the ChangeEvent alias into a named OBJECT.
--   OBJECT_CONSTRUCT(ChangeEventMetrics.*) does the same for the combined metrics alias.
--   The qualified wildcard (alias.*) ensures each OBJECT only contains columns from its own source.
--   Adding a column upstream (a new metric file + combiner regen) expands the OBJECT automatically —
--   nothing downstream breaks.
--
--   NOTE: bare OBJECT_CONSTRUCT(*) after a JOIN is WRONG — it packs ALL joined columns into BOTH objects.
--   Always qualify with the alias: OBJECT_CONSTRUCT(ChangeEvent.*), OBJECT_CONSTRUCT(ChangeEventMetrics.*).
-- Consumer access: ChangeEventWide.ChangeEvent:<Field> / ChangeEventWide.ChangeEventMetrics:<MetricName> / ...

SELECT
    OBJECT_CONSTRUCT(ChangeEvent.*) AS ChangeEvent
    , OBJECT_CONSTRUCT(ChangeEventMetrics.*) AS ChangeEventMetrics
FROM {{ ref('ChangeEventRaw') }} AS ChangeEvent
LEFT JOIN {{ ref('change_event_metrics') }} AS ChangeEventMetrics
    ON ChangeEvent.ID = ChangeEventMetrics.ID
