-- WIDE LAYER: Contact Wide Table
-- AUTO-GENERATED by tools/generate_wide_layer.py — DO NOT EDIT BY HAND.
-- Regenerate after adding/removing a file in models/metric_layer/Contact_Metrics/:
--   python3 tools/generate_wide_layer.py --entity Contact
-- Auto-assembly: one OBJECT per relation (raw + each metric model).
-- No combiner. No hand-maintained column list. Metric OBJECTs carry the
-- measure only — the join key ID is implicit (never selected from the
-- metric model directly, so it never needs stripping).
-- Consumer access: ContactWide.Contact:<Field> / ContactWide.<MetricName>:<MetricName> / ...

SELECT
    Contact.Contact AS Contact
FROM {{ ref('ContactRaw') }} AS Contact
