-- WIDE LAYER: Contact Wide Table (AUTO-GENERATED)
-- AUTO-GENERATED by tools/generate_wide_layer.py — DO NOT EDIT BY HAND.
-- Snowflake OBJECT_CONSTRUCT(alias.*) — qualified wildcard, auto-expanding.
-- No explicit column list, no logic, zero maintenance.
-- Regenerate after adding/removing a file in models/metric_layer/Contact_Metrics/:
--   python3 tools/generate_metrics_combiner.py --entity Contact
--   python3 tools/generate_wide_layer.py --entity Contact
-- (run the combiner generator FIRST — the wide layer joins against
-- its output, contact_metrics, not the individual metric files.)
-- Owner: CI/CD (mechanically generated, do not edit by hand)
--
-- HOW IT WORKS (Snowflake):
--   OBJECT_CONSTRUCT(Contact.*) packs the entire row from the Contact alias into a named OBJECT.
--   OBJECT_CONSTRUCT(ContactMetrics.*) does the same for the combined metrics alias.
--   The qualified wildcard (alias.*) ensures each OBJECT only contains columns from its own source.
--   Adding a column upstream (a new metric file + combiner regen) expands the OBJECT automatically —
--   nothing downstream breaks.
--
--   NOTE: bare OBJECT_CONSTRUCT(*) after a JOIN is WRONG — it packs ALL joined columns into BOTH objects.
--   Always qualify with the alias: OBJECT_CONSTRUCT(Contact.*), OBJECT_CONSTRUCT(ContactMetrics.*).
-- Consumer access: ContactWide.Contact:<Field> / ContactWide.ContactMetrics:<MetricName> / ...

SELECT
    OBJECT_CONSTRUCT(Contact.*) AS Contact
    , OBJECT_CONSTRUCT(ContactMetrics.*) AS ContactMetrics
FROM {{ ref('ContactRaw') }} AS Contact
LEFT JOIN {{ ref('contact_metrics') }} AS ContactMetrics
    ON Contact.ID = ContactMetrics.ID
