-- WIDE LAYER: Policy Wide Table (AUTO-GENERATED)
-- AUTO-GENERATED by tools/generate_wide_layer.py — DO NOT EDIT BY HAND.
-- Snowflake OBJECT_CONSTRUCT(alias.*) — qualified wildcard, auto-expanding.
-- No explicit column list, no logic, zero maintenance.
-- Regenerate after adding/removing a file in models/metric_layer/Policy_Metrics/:
--   python3 tools/generate_metrics_combiner.py --entity Policy
--   python3 tools/generate_wide_layer.py --entity Policy
-- (run the combiner generator FIRST — the wide layer joins against
-- its output, policy_metrics, not the individual metric files.)
-- Owner: CI/CD (mechanically generated, do not edit by hand)
--
-- HOW IT WORKS (Snowflake):
--   OBJECT_CONSTRUCT(Policy.*) packs the entire row from the Policy alias into a named OBJECT.
--   OBJECT_CONSTRUCT(PolicyMetrics.*) does the same for the combined metrics alias.
--   The qualified wildcard (alias.*) ensures each OBJECT only contains columns from its own source.
--   Adding a column upstream (a new metric file + combiner regen) expands the OBJECT automatically —
--   nothing downstream breaks.
--
--   NOTE: bare OBJECT_CONSTRUCT(*) after a JOIN is WRONG — it packs ALL joined columns into BOTH objects.
--   Always qualify with the alias: OBJECT_CONSTRUCT(Policy.*), OBJECT_CONSTRUCT(PolicyMetrics.*).
-- Consumer access: PolicyWide.Policy:<Field> / PolicyWide.PolicyMetrics:<MetricName> / ...

SELECT
    OBJECT_CONSTRUCT(Policy.*) AS Policy
    , OBJECT_CONSTRUCT(PolicyMetrics.*) AS PolicyMetrics
FROM {{ ref('PolicyRaw') }} AS Policy
INNER JOIN {{ ref('policy_metrics') }} AS PolicyMetrics
    ON Policy.ID = PolicyMetrics.ID
