-- WIDE LAYER: Policy Wide Table
-- AUTO-GENERATED by tools/generate_wide_layer.py — DO NOT EDIT BY HAND.
-- Regenerate after adding/removing a file in models/metric_layer/Policy_Metrics/:
--   python3 tools/generate_wide_layer.py --entity Policy
-- Auto-assembly: one OBJECT per relation (raw + each metric model).
-- No combiner. No hand-maintained column list. Metric OBJECTs carry the
-- measure only — the join key ID is implicit (never selected from the
-- metric model directly, so it never needs stripping).
-- Consumer access: PolicyWide.Policy:<Field> / PolicyWide.<MetricName>:<MetricName> / ...

SELECT
    Policy.Policy AS Policy
    , OBJECT_CONSTRUCT_KEEP_NULL('AgentChangeRetentionRate90Days', AgentChangeRetentionRate90Days.AgentChangeRetentionRate90Days)::OBJECT(AgentChangeRetentionRate90Days FLOAT) AS AgentChangeRetentionRate90Days
    , OBJECT_CONSTRUCT_KEEP_NULL('InForce90Flag', InForce90Flag.InForce90Flag)::OBJECT(InForce90Flag NUMBER) AS InForce90Flag
    , OBJECT_CONSTRUCT_KEEP_NULL('InceptionMonth', InceptionMonth.InceptionMonth)::OBJECT(InceptionMonth VARCHAR) AS InceptionMonth
    , OBJECT_CONSTRUCT_KEEP_NULL('MovedPolicyRetentionRate90Days', MovedPolicyRetentionRate90Days.MovedPolicyRetentionRate90Days)::OBJECT(MovedPolicyRetentionRate90Days FLOAT) AS MovedPolicyRetentionRate90Days
    , OBJECT_CONSTRUCT_KEEP_NULL('NumberOfAgentChangeEvents', NumberOfAgentChangeEvents.NumberOfAgentChangeEvents)::OBJECT(NumberOfAgentChangeEvents NUMBER) AS NumberOfAgentChangeEvents
    , OBJECT_CONSTRUCT_KEEP_NULL('NumberOfAgentChangePoliciesInForce90Days', NumberOfAgentChangePoliciesInForce90Days.NumberOfAgentChangePoliciesInForce90Days)::OBJECT(NumberOfAgentChangePoliciesInForce90Days NUMBER) AS NumberOfAgentChangePoliciesInForce90Days
    , OBJECT_CONSTRUCT_KEEP_NULL('NumberOfMovedPoliciesInForce90Days', NumberOfMovedPoliciesInForce90Days.NumberOfMovedPoliciesInForce90Days)::OBJECT(NumberOfMovedPoliciesInForce90Days NUMBER) AS NumberOfMovedPoliciesInForce90Days
    , OBJECT_CONSTRUCT_KEEP_NULL('NumberOfPoliciesInForce', NumberOfPoliciesInForce.NumberOfPoliciesInForce)::OBJECT(NumberOfPoliciesInForce NUMBER) AS NumberOfPoliciesInForce
    , OBJECT_CONSTRUCT_KEEP_NULL('NumberOfZipChangeEvents', NumberOfZipChangeEvents.NumberOfZipChangeEvents)::OBJECT(NumberOfZipChangeEvents NUMBER) AS NumberOfZipChangeEvents
    , OBJECT_CONSTRUCT_KEEP_NULL('TenureDays', TenureDays.TenureDays)::OBJECT(TenureDays NUMBER) AS TenureDays
    , OBJECT_CONSTRUCT_KEEP_NULL('TermType', TermType.TermType)::OBJECT(TermType VARCHAR) AS TermType
FROM {{ ref('PolicyRaw') }} AS Policy
INNER JOIN {{ ref('AgentChangeRetentionRate90Days') }} AS AgentChangeRetentionRate90Days
    ON Policy.ID = AgentChangeRetentionRate90Days.ID
INNER JOIN {{ ref('InForce90Flag') }} AS InForce90Flag
    ON Policy.ID = InForce90Flag.ID
INNER JOIN {{ ref('InceptionMonth') }} AS InceptionMonth
    ON Policy.ID = InceptionMonth.ID
INNER JOIN {{ ref('MovedPolicyRetentionRate90Days') }} AS MovedPolicyRetentionRate90Days
    ON Policy.ID = MovedPolicyRetentionRate90Days.ID
INNER JOIN {{ ref('NumberOfAgentChangeEvents') }} AS NumberOfAgentChangeEvents
    ON Policy.ID = NumberOfAgentChangeEvents.ID
INNER JOIN {{ ref('NumberOfAgentChangePoliciesInForce90Days') }} AS NumberOfAgentChangePoliciesInForce90Days
    ON Policy.ID = NumberOfAgentChangePoliciesInForce90Days.ID
INNER JOIN {{ ref('NumberOfMovedPoliciesInForce90Days') }} AS NumberOfMovedPoliciesInForce90Days
    ON Policy.ID = NumberOfMovedPoliciesInForce90Days.ID
INNER JOIN {{ ref('NumberOfPoliciesInForce') }} AS NumberOfPoliciesInForce
    ON Policy.ID = NumberOfPoliciesInForce.ID
INNER JOIN {{ ref('NumberOfZipChangeEvents') }} AS NumberOfZipChangeEvents
    ON Policy.ID = NumberOfZipChangeEvents.ID
INNER JOIN {{ ref('TenureDays') }} AS TenureDays
    ON Policy.ID = TenureDays.ID
INNER JOIN {{ ref('TermType') }} AS TermType
    ON Policy.ID = TermType.ID
