-- WIDE LAYER: Survey Wide Table
-- AUTO-GENERATED by tools/generate_wide_layer.py — DO NOT EDIT BY HAND.
-- Regenerate after adding/removing a file in models/metric_layer/Survey_Metrics/:
--   python3 tools/generate_wide_layer.py --entity Survey
-- Auto-assembly: one OBJECT per relation (raw + each metric model).
-- No combiner. No hand-maintained column list. Metric OBJECTs carry the
-- measure only — the join key ID is implicit (never selected from the
-- metric model directly, so it never needs stripping).
-- Consumer access: SurveyWide.Survey:<Field> / SurveyWide.<MetricName>:<MetricName> / ...

SELECT
    Survey.Survey AS Survey
    , OBJECT_CONSTRUCT_KEEP_NULL('AgentChangeAvgDaysWithoutAgent', AgentChangeAvgDaysWithoutAgent.AgentChangeAvgDaysWithoutAgent)::OBJECT(AgentChangeAvgDaysWithoutAgent FLOAT) AS AgentChangeAvgDaysWithoutAgent
    , OBJECT_CONSTRUCT_KEEP_NULL('AgentChangeAvgNps', AgentChangeAvgNps.AgentChangeAvgNps)::OBJECT(AgentChangeAvgNps FLOAT) AS AgentChangeAvgNps
    , OBJECT_CONSTRUCT_KEEP_NULL('AgentChangeMeetsNeedsRate', AgentChangeMeetsNeedsRate.AgentChangeMeetsNeedsRate)::OBJECT(AgentChangeMeetsNeedsRate FLOAT) AS AgentChangeMeetsNeedsRate
    , OBJECT_CONSTRUCT_KEEP_NULL('AgentChangeNoCommsRate', AgentChangeNoCommsRate.AgentChangeNoCommsRate)::OBJECT(AgentChangeNoCommsRate FLOAT) AS AgentChangeNoCommsRate
    , OBJECT_CONSTRUCT_KEEP_NULL('AgentChangeResponseRate', AgentChangeResponseRate.AgentChangeResponseRate)::OBJECT(AgentChangeResponseRate VARCHAR) AS AgentChangeResponseRate
    , OBJECT_CONSTRUCT_KEEP_NULL('CssCesAvgScore', CssCesAvgScore.CssCesAvgScore)::OBJECT(CssCesAvgScore FLOAT) AS CssCesAvgScore
    , OBJECT_CONSTRUCT_KEEP_NULL('NewBusinessAvgNps', NewBusinessAvgNps.NewBusinessAvgNps)::OBJECT(NewBusinessAvgNps FLOAT) AS NewBusinessAvgNps
    , OBJECT_CONSTRUCT_KEEP_NULL('RenewalAvgNps', RenewalAvgNps.RenewalAvgNps)::OBJECT(RenewalAvgNps FLOAT) AS RenewalAvgNps
    , OBJECT_CONSTRUCT_KEEP_NULL('RnpsAvgNps', RnpsAvgNps.RnpsAvgNps)::OBJECT(RnpsAvgNps FLOAT) AS RnpsAvgNps
FROM {{ ref('SurveyRaw') }} AS Survey
LEFT JOIN {{ ref('AgentChangeAvgDaysWithoutAgent') }} AS AgentChangeAvgDaysWithoutAgent
    ON Survey.ID = AgentChangeAvgDaysWithoutAgent.ID
LEFT JOIN {{ ref('AgentChangeAvgNps') }} AS AgentChangeAvgNps
    ON Survey.ID = AgentChangeAvgNps.ID
LEFT JOIN {{ ref('AgentChangeMeetsNeedsRate') }} AS AgentChangeMeetsNeedsRate
    ON Survey.ID = AgentChangeMeetsNeedsRate.ID
LEFT JOIN {{ ref('AgentChangeNoCommsRate') }} AS AgentChangeNoCommsRate
    ON Survey.ID = AgentChangeNoCommsRate.ID
LEFT JOIN {{ ref('AgentChangeResponseRate') }} AS AgentChangeResponseRate
    ON Survey.ID = AgentChangeResponseRate.ID
LEFT JOIN {{ ref('CssCesAvgScore') }} AS CssCesAvgScore
    ON Survey.ID = CssCesAvgScore.ID
LEFT JOIN {{ ref('NewBusinessAvgNps') }} AS NewBusinessAvgNps
    ON Survey.ID = NewBusinessAvgNps.ID
LEFT JOIN {{ ref('RenewalAvgNps') }} AS RenewalAvgNps
    ON Survey.ID = RenewalAvgNps.ID
LEFT JOIN {{ ref('RnpsAvgNps') }} AS RnpsAvgNps
    ON Survey.ID = RnpsAvgNps.ID
