-- WIDE LAYER: Survey Wide Table (AUTO-GENERATED)
-- AUTO-GENERATED by tools/generate_wide_layer.py — DO NOT EDIT BY HAND.
-- Snowflake OBJECT_CONSTRUCT(alias.*) — qualified wildcard, auto-expanding.
-- No explicit column list, no logic, zero maintenance.
-- Regenerate after adding/removing a file in models/metric_layer/Survey_Metrics/:
--   python3 tools/generate_metrics_combiner.py --entity Survey
--   python3 tools/generate_wide_layer.py --entity Survey
-- (run the combiner generator FIRST — the wide layer joins against
-- its output, survey_metrics, not the individual metric files.)
-- Owner: CI/CD (mechanically generated, do not edit by hand)
--
-- HOW IT WORKS (Snowflake):
--   OBJECT_CONSTRUCT(Survey.*) packs the entire row from the Survey alias into a named OBJECT.
--   OBJECT_CONSTRUCT(SurveyMetrics.*) does the same for the combined metrics alias.
--   The qualified wildcard (alias.*) ensures each OBJECT only contains columns from its own source.
--   Adding a column upstream (a new metric file + combiner regen) expands the OBJECT automatically —
--   nothing downstream breaks.
--
--   NOTE: bare OBJECT_CONSTRUCT(*) after a JOIN is WRONG — it packs ALL joined columns into BOTH objects.
--   Always qualify with the alias: OBJECT_CONSTRUCT(Survey.*), OBJECT_CONSTRUCT(SurveyMetrics.*).
-- Consumer access: SurveyWide.Survey:<Field> / SurveyWide.SurveyMetrics:<MetricName> / ...

SELECT
    OBJECT_CONSTRUCT(Survey.*) AS Survey
    , OBJECT_CONSTRUCT(SurveyMetrics.*) AS SurveyMetrics
FROM {{ ref('SurveyRaw') }} AS Survey
LEFT JOIN {{ ref('survey_metrics') }} AS SurveyMetrics
    ON Survey.ID = SurveyMetrics.ID
