-- METRIC COMBINER: ChangeEvent Metrics (AUTO-GENERATED)
-- AUTO-GENERATED by tools/generate_metrics_combiner.py — DO NOT EDIT BY HAND.
-- Regenerate after adding/removing a file in models/metric_layer/ChangeEvent_Metrics/:
--   python3 tools/generate_metrics_combiner.py --entity ChangeEvent
-- Assembled from every individual metric file in ChangeEvent_Metrics/.
-- Contract: 1 row per ChangeEventRaw ID, every metric as a column.
-- LEFT JOIN per metric (defensive — a metric missing a row zero-fills
-- via COALESCE where a safe default exists; otherwise passes NULL
-- through, e.g. survey-average metrics where NULL means 'no response',
-- never a real zero score).

WITH InForce90DaysAfterChangeFlag AS (
    SELECT * FROM {{ ref('InForce90DaysAfterChangeFlag') }}
)
, IsAgentChangeEvent AS (
    SELECT * FROM {{ ref('IsAgentChangeEvent') }}
)
, IsZipChangeEvent AS (
    SELECT * FROM {{ ref('IsZipChangeEvent') }}
)

SELECT
    ChangeEvent.ID
    , COALESCE(InForce90DaysAfterChangeFlag.InForce90DaysAfterChangeFlag, 0) AS InForce90DaysAfterChangeFlag
    , COALESCE(IsAgentChangeEvent.IsAgentChangeEvent, 0) AS IsAgentChangeEvent
    , COALESCE(IsZipChangeEvent.IsZipChangeEvent, 0) AS IsZipChangeEvent
FROM {{ ref('ChangeEventRaw') }} AS ChangeEvent
LEFT JOIN InForce90DaysAfterChangeFlag
    ON ChangeEvent.ID = InForce90DaysAfterChangeFlag.ID
LEFT JOIN IsAgentChangeEvent
    ON ChangeEvent.ID = IsAgentChangeEvent.ID
LEFT JOIN IsZipChangeEvent
    ON ChangeEvent.ID = IsZipChangeEvent.ID
