-- METRIC COMBINER: Contact Metrics (AUTO-GENERATED)
-- AUTO-GENERATED by tools/generate_metrics_combiner.py — DO NOT EDIT BY HAND.
-- Regenerate after adding/removing a file in models/metric_layer/Contact_Metrics/:
--   python3 tools/generate_metrics_combiner.py --entity Contact
-- Assembled from every individual metric file in Contact_Metrics/.
-- Contract: 1 row per ContactRaw ID, every metric as a column.
-- LEFT JOIN per metric (defensive — a metric missing a row zero-fills
-- via COALESCE where a safe default exists; otherwise passes NULL
-- through, e.g. survey-average metrics where NULL means 'no response',
-- never a real zero score).

SELECT
    Contact.ID
FROM {{ ref('ContactRaw') }} AS Contact
