-- METRIC COMBINER: Policy Metrics (AUTO-GENERATED)
-- AUTO-GENERATED by tools/generate_metrics_combiner.py — DO NOT EDIT BY HAND.
-- Regenerate after adding/removing a file in models/metric_layer/Policy_Metrics/:
--   python3 tools/generate_metrics_combiner.py --entity Policy
-- Assembled from every individual metric file in Policy_Metrics/.
-- Contract: 1 row per PolicyRaw ID, every metric as a column.
-- LEFT JOIN per metric (defensive — a metric missing a row zero-fills
-- via COALESCE where a safe default exists; otherwise passes NULL
-- through, e.g. survey-average metrics where NULL means 'no response',
-- never a real zero score).

WITH AgentChangeCsatScore AS (
    SELECT * FROM {{ ref('AgentChangeCsatScore') }}
)
, AgentChangeDaysWithoutAgent AS (
    SELECT * FROM {{ ref('AgentChangeDaysWithoutAgent') }}
)
, AgentChangeMeetsNeedsFlag AS (
    SELECT * FROM {{ ref('AgentChangeMeetsNeedsFlag') }}
)
, AgentChangeReceivedLetterFlag AS (
    SELECT * FROM {{ ref('AgentChangeReceivedLetterFlag') }}
)
, AgentChangeRetentionRate90Days AS (
    SELECT * FROM {{ ref('AgentChangeRetentionRate90Days') }}
)
, CssCesScore AS (
    SELECT * FROM {{ ref('CssCesScore') }}
)
, InForce90Flag AS (
    SELECT * FROM {{ ref('InForce90Flag') }}
)
, InceptionMonth AS (
    SELECT * FROM {{ ref('InceptionMonth') }}
)
, LoadMonth AS (
    SELECT * FROM {{ ref('LoadMonth') }}
)
, MovedPolicyRetentionRate90Days AS (
    SELECT * FROM {{ ref('MovedPolicyRetentionRate90Days') }}
)
, NumberOfAgentChangeEvents AS (
    SELECT * FROM {{ ref('NumberOfAgentChangeEvents') }}
)
, NumberOfAgentChangePoliciesInForce90Days AS (
    SELECT * FROM {{ ref('NumberOfAgentChangePoliciesInForce90Days') }}
)
, NumberOfMovedPoliciesInForce90Days AS (
    SELECT * FROM {{ ref('NumberOfMovedPoliciesInForce90Days') }}
)
, NumberOfPoliciesInForce AS (
    SELECT * FROM {{ ref('NumberOfPoliciesInForce') }}
)
, NumberOfZipChangeEvents AS (
    SELECT * FROM {{ ref('NumberOfZipChangeEvents') }}
)
, OnboardingNpsScore AS (
    SELECT * FROM {{ ref('OnboardingNpsScore') }}
)
, RenewalNpsScore AS (
    SELECT * FROM {{ ref('RenewalNpsScore') }}
)
, RnpsScore AS (
    SELECT * FROM {{ ref('RnpsScore') }}
)
, TenureDays AS (
    SELECT * FROM {{ ref('TenureDays') }}
)
, TermType AS (
    SELECT * FROM {{ ref('TermType') }}
)

SELECT
    Policy.ID
    , COALESCE(AgentChangeCsatScore.AgentChangeCsatScore, 0) AS AgentChangeCsatScore
    , COALESCE(AgentChangeDaysWithoutAgent.AgentChangeDaysWithoutAgent, 0) AS AgentChangeDaysWithoutAgent
    , COALESCE(AgentChangeMeetsNeedsFlag.AgentChangeMeetsNeedsFlag, 0) AS AgentChangeMeetsNeedsFlag
    , COALESCE(AgentChangeReceivedLetterFlag.AgentChangeReceivedLetterFlag, 0) AS AgentChangeReceivedLetterFlag
    , AgentChangeRetentionRate90Days.AgentChangeRetentionRate90Days
    , COALESCE(CssCesScore.CssCesScore, 0) AS CssCesScore
    , COALESCE(InForce90Flag.InForce90Flag, 0) AS InForce90Flag
    , InceptionMonth.InceptionMonth
    , LoadMonth.LoadMonth
    , MovedPolicyRetentionRate90Days.MovedPolicyRetentionRate90Days
    , COALESCE(NumberOfAgentChangeEvents.NumberOfAgentChangeEvents, 0) AS NumberOfAgentChangeEvents
    , COALESCE(NumberOfAgentChangePoliciesInForce90Days.NumberOfAgentChangePoliciesInForce90Days, 0) AS NumberOfAgentChangePoliciesInForce90Days
    , COALESCE(NumberOfMovedPoliciesInForce90Days.NumberOfMovedPoliciesInForce90Days, 0) AS NumberOfMovedPoliciesInForce90Days
    , COALESCE(NumberOfPoliciesInForce.NumberOfPoliciesInForce, 0) AS NumberOfPoliciesInForce
    , COALESCE(NumberOfZipChangeEvents.NumberOfZipChangeEvents, 0) AS NumberOfZipChangeEvents
    , COALESCE(OnboardingNpsScore.OnboardingNpsScore, 0) AS OnboardingNpsScore
    , COALESCE(RenewalNpsScore.RenewalNpsScore, 0) AS RenewalNpsScore
    , COALESCE(RnpsScore.RnpsScore, 0) AS RnpsScore
    , TenureDays.TenureDays
    , TermType.TermType
FROM {{ ref('PolicyRaw') }} AS Policy
LEFT JOIN AgentChangeCsatScore
    ON Policy.ID = AgentChangeCsatScore.ID
LEFT JOIN AgentChangeDaysWithoutAgent
    ON Policy.ID = AgentChangeDaysWithoutAgent.ID
LEFT JOIN AgentChangeMeetsNeedsFlag
    ON Policy.ID = AgentChangeMeetsNeedsFlag.ID
LEFT JOIN AgentChangeReceivedLetterFlag
    ON Policy.ID = AgentChangeReceivedLetterFlag.ID
LEFT JOIN AgentChangeRetentionRate90Days
    ON Policy.ID = AgentChangeRetentionRate90Days.ID
LEFT JOIN CssCesScore
    ON Policy.ID = CssCesScore.ID
LEFT JOIN InForce90Flag
    ON Policy.ID = InForce90Flag.ID
LEFT JOIN InceptionMonth
    ON Policy.ID = InceptionMonth.ID
LEFT JOIN LoadMonth
    ON Policy.ID = LoadMonth.ID
LEFT JOIN MovedPolicyRetentionRate90Days
    ON Policy.ID = MovedPolicyRetentionRate90Days.ID
LEFT JOIN NumberOfAgentChangeEvents
    ON Policy.ID = NumberOfAgentChangeEvents.ID
LEFT JOIN NumberOfAgentChangePoliciesInForce90Days
    ON Policy.ID = NumberOfAgentChangePoliciesInForce90Days.ID
LEFT JOIN NumberOfMovedPoliciesInForce90Days
    ON Policy.ID = NumberOfMovedPoliciesInForce90Days.ID
LEFT JOIN NumberOfPoliciesInForce
    ON Policy.ID = NumberOfPoliciesInForce.ID
LEFT JOIN NumberOfZipChangeEvents
    ON Policy.ID = NumberOfZipChangeEvents.ID
LEFT JOIN OnboardingNpsScore
    ON Policy.ID = OnboardingNpsScore.ID
LEFT JOIN RenewalNpsScore
    ON Policy.ID = RenewalNpsScore.ID
LEFT JOIN RnpsScore
    ON Policy.ID = RnpsScore.ID
LEFT JOIN TenureDays
    ON Policy.ID = TenureDays.ID
LEFT JOIN TermType
    ON Policy.ID = TermType.ID
