-- METRIC COMBINER: Survey Metrics (AUTO-GENERATED)
-- AUTO-GENERATED by tools/generate_metrics_combiner.py — DO NOT EDIT BY HAND.
-- Regenerate after adding/removing a file in models/metric_layer/Survey_Metrics/:
--   python3 tools/generate_metrics_combiner.py --entity Survey
-- Assembled from every individual metric file in Survey_Metrics/.
-- Contract: 1 row per SurveyRaw ID, every metric as a column.
-- LEFT JOIN per metric (defensive — a metric missing a row zero-fills
-- via COALESCE where a safe default exists; otherwise passes NULL
-- through, e.g. survey-average metrics where NULL means 'no response',
-- never a real zero score).

WITH AgentChangeAvgDaysWithoutAgent AS (
    SELECT * FROM {{ ref('AgentChangeAvgDaysWithoutAgent') }}
)
, AgentChangeAvgNps AS (
    SELECT * FROM {{ ref('AgentChangeAvgNps') }}
)
, AgentChangeMeetsNeedsRate AS (
    SELECT * FROM {{ ref('AgentChangeMeetsNeedsRate') }}
)
, AgentChangeNoCommsRate AS (
    SELECT * FROM {{ ref('AgentChangeNoCommsRate') }}
)
, AgentChangeResponseRate AS (
    SELECT * FROM {{ ref('AgentChangeResponseRate') }}
)
, CssCesAvgScore AS (
    SELECT * FROM {{ ref('CssCesAvgScore') }}
)
, NewBusinessAvgNps AS (
    SELECT * FROM {{ ref('NewBusinessAvgNps') }}
)
, RenewalAvgNps AS (
    SELECT * FROM {{ ref('RenewalAvgNps') }}
)
, RnpsAvgNps AS (
    SELECT * FROM {{ ref('RnpsAvgNps') }}
)

SELECT
    Survey.ID
    , AgentChangeAvgDaysWithoutAgent.AgentChangeAvgDaysWithoutAgent
    , AgentChangeAvgNps.AgentChangeAvgNps
    , AgentChangeMeetsNeedsRate.AgentChangeMeetsNeedsRate
    , AgentChangeNoCommsRate.AgentChangeNoCommsRate
    , AgentChangeResponseRate.AgentChangeResponseRate
    , CssCesAvgScore.CssCesAvgScore
    , NewBusinessAvgNps.NewBusinessAvgNps
    , RenewalAvgNps.RenewalAvgNps
    , RnpsAvgNps.RnpsAvgNps
FROM {{ ref('SurveyRaw') }} AS Survey
LEFT JOIN AgentChangeAvgDaysWithoutAgent
    ON Survey.ID = AgentChangeAvgDaysWithoutAgent.ID
LEFT JOIN AgentChangeAvgNps
    ON Survey.ID = AgentChangeAvgNps.ID
LEFT JOIN AgentChangeMeetsNeedsRate
    ON Survey.ID = AgentChangeMeetsNeedsRate.ID
LEFT JOIN AgentChangeNoCommsRate
    ON Survey.ID = AgentChangeNoCommsRate.ID
LEFT JOIN AgentChangeResponseRate
    ON Survey.ID = AgentChangeResponseRate.ID
LEFT JOIN CssCesAvgScore
    ON Survey.ID = CssCesAvgScore.ID
LEFT JOIN NewBusinessAvgNps
    ON Survey.ID = NewBusinessAvgNps.ID
LEFT JOIN RenewalAvgNps
    ON Survey.ID = RenewalAvgNps.ID
LEFT JOIN RnpsAvgNps
    ON Survey.ID = RnpsAvgNps.ID
